"""Dashboard dimension catalog (single source of truth).

Each dimension maps a short indicator key used by the frontend/snapshot schema
to a World Bank WDI v2 indicator code, grouping metadata, and normalization
rules for storage in the offline snapshot.
"""

from __future__ import annotations

DIMENSIONS = [
    {
        "key": "gdp",
        "label": "GDP",
        "wb_code": "NY.GDP.MKTP.CD",
        "group": "economy",
        "group_label": "Economy",
        "unit": "T$",
        "scale": 1e12,
        "decimals": 2,
        "good_when": "high",
        "description": "Gross domestic product, current USD",
    },
    {
        "key": "gdp_growth",
        "label": "GDP growth",
        "wb_code": "NY.GDP.MKTP.KD.ZG",
        "group": "economy",
        "group_label": "Economy",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Annual GDP growth (constant prices)",
    },
    {
        "key": "cpi",
        "label": "Inflation",
        "wb_code": "FP.CPI.TOTL.ZG",
        "group": "economy",
        "group_label": "Economy",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "low",
        "description": "Inflation, consumer prices (annual %)",
    },
    {
        "key": "unemployment",
        "label": "Unemployment",
        "wb_code": "SL.UEM.TOTL.ZS",
        "group": "economy",
        "group_label": "Economy",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "low",
        "description": "Unemployment, total (% of labor force)",
    },
    {
        "key": "debt",
        "label": "Govt debt %GDP",
        "wb_code": "GC.DOD.TOTL.GD.ZS",
        "group": "economy",
        "group_label": "Economy",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "low",
        "description": "Central government debt, total (% of GDP)",
    },
    {
        "key": "trade",
        "label": "Trade %GDP",
        "wb_code": "NE.TRD.GNFS.ZS",
        "group": "trade_finance",
        "group_label": "Trade & Finance",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "neutral",
        "description": "Trade (% of GDP)",
    },
    {
        "key": "fdi",
        "label": "FDI inflows %GDP",
        "wb_code": "BX.KLT.DINV.WD.GD.ZS",
        "group": "trade_finance",
        "group_label": "Trade & Finance",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "neutral",
        "description": "Foreign direct investment, net inflows (% of GDP)",
    },
    {
        "key": "savings",
        "label": "Gross savings %GDP",
        "wb_code": "NY.GNS.ICTR.ZS",
        "group": "trade_finance",
        "group_label": "Trade & Finance",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Gross savings (% of GDP)",
    },
    {
        "key": "tax",
        "label": "Tax revenue %GDP",
        "wb_code": "GC.TAX.TOTL.GD.ZS",
        "group": "trade_finance",
        "group_label": "Trade & Finance",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "neutral",
        "description": "Tax revenue (% of GDP)",
    },
    {
        "key": "reserves",
        "label": "Reserves",
        "wb_code": "FI.RES.TOTL.CD",
        "group": "trade_finance",
        "group_label": "Trade & Finance",
        "unit": "B$",
        "scale": 1e9,
        "decimals": 2,
        "good_when": "high",
        "description": "Total reserves (includes gold), current USD",
    },
    {
        "key": "pop_total",
        "label": "Population",
        "wb_code": "SP.POP.TOTL",
        "group": "society",
        "group_label": "Society",
        "unit": "M",
        "scale": 1e6,
        "decimals": 2,
        "good_when": "high",
        "description": "Population, total",
    },
    {
        "key": "pop_aging",
        "label": "65+ %",
        "wb_code": "SP.POP.65UP.TO.ZS",
        "group": "society",
        "group_label": "Society",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "neutral",
        "description": "Population ages 65 and above (% of total)",
    },
    {
        "key": "urban",
        "label": "Urban population %",
        "wb_code": "SP.URB.TOTL.IN.ZS",
        "group": "society",
        "group_label": "Society",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Urban population (% of total)",
    },
    {
        "key": "life_exp",
        "label": "Life expectancy",
        "wb_code": "SP.DYN.LE00.IN",
        "group": "society",
        "group_label": "Society",
        "unit": "yrs",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Life expectancy at birth, total (years)",
    },
    {
        "key": "health",
        "label": "Health expenditure %GDP",
        "wb_code": "SH.XPD.CHEX.GD.ZS",
        "group": "society",
        "group_label": "Society",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Current health expenditure (% of GDP)",
    },
    {
        "key": "rd",
        "label": "R&D expenditure %GDP",
        "wb_code": "GB.XPD.RSDV.GD.ZS",
        "group": "innovation_environment",
        "group_label": "Innovation & Environment",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Research and development expenditure (% of GDP)",
    },
    {
        "key": "internet",
        "label": "Internet users %",
        "wb_code": "IT.NET.USER.ZS",
        "group": "innovation_environment",
        "group_label": "Innovation & Environment",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Individuals using the Internet (% of population)",
    },
    {
        "key": "education",
        "label": "Education spending %GDP",
        "wb_code": "SE.XPD.TOTL.GD.ZS",
        "group": "innovation_environment",
        "group_label": "Innovation & Environment",
        "unit": "%",
        "scale": None,
        "decimals": 2,
        "good_when": "high",
        "description": "Government expenditure on education, total (% of GDP)",
    },
    {
        "key": "energy",
        "label": "Energy use kgoe/cap",
        "wb_code": "EG.USE.PCAP.KG.OE",
        "group": "innovation_environment",
        "group_label": "Innovation & Environment",
        "unit": "kgoe",
        "scale": None,
        "decimals": 2,
        "good_when": "neutral",
        "description": "Energy use (kg of oil equivalent per capita)",
    },
    {
        "key": "co2",
        "label": "CO2 per capita",
        "wb_code": "EN.GHG.CO2.PC.CE.AR5",
        "group": "innovation_environment",
        "group_label": "Innovation & Environment",
        "unit": "tCO2",
        "scale": None,
        "decimals": 2,
        "good_when": "low",
        "description": "CO2 emissions (metric tons per capita, AR5 methodology)",
    },
]

GROUPS = ["economy", "trade_finance", "society", "innovation_environment"]

GROUP_LABELS = {
    "economy": "Economy",
    "trade_finance": "Trade & Finance",
    "society": "Society",
    "innovation_environment": "Innovation & Environment",
}
